title: C Programming
description: A C Programming Documentation.
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme

url: "https://xrito-o.github.io"  # No trailing slash
baseurl: "/C-programming"                   # The subfolder name, starts with /



aux_links:
  Github Repository: https://github.com/xrito-o/C-programming/

color_scheme: dark

includes_dir: _includes
